### PR TITLE
Womens stats

### PR DESCRIPTION
**Pull request by OscarLane**
Hi @jimmyday12 ,

Submitting the pull request for womens stats, not sure whether you want to put it straight into master or put it on develop/it's own branch: up to you!

All R functions are in the [R/womens_stats.R](https://github.com/OscarLane/fitzRoy/blob/womens-stats/R/womens_stats.R) file, and tests in [tests/testthat/test-womens-stats.R](https://github.com/OscarLane/fitzRoy/blob/womens-stats/tests/testthat/test-womens_stats.R).

There's also a vignette in [vignettes/womens-stats.md](https://github.com/OscarLane/fitzRoy/blob/womens-stats/vignettes/womens-stats.md), though everything above the "Match Data" section I've made into internal functions. I've kept as is for the time being so you can see how things work under the hood, but might remove those parts before publishing the vignette.

Let me know if you need any changes before merging.

Oscar

### CODE REVIEW

**Comment by jimmyday12** [comment]
Thanks @OscarLane - I'm going to try review one night this week but all looks awesome! Might merge a couple changes I've got in develop with this and then merge all of that into master. I'll keep you posted.

**Comment by OscarLane** [comment]
Have discovered that since this pull request, 2019 round fixtures have been added to the website, which has broken `get_aflw_round_data()`, as it expects match data to be present. I've pushed some fixes to womens-stats.

**Comment by jimmyday12** [comment]
Hey @OscarLane this all looks great and ready to merge in. I'll put a tweet out and maybe a blog post this weekend!

**Comment by OscarLane** [comment]
Great! I notice that the vignette has also been broken a bit because of those latest changes, so I'll try and redo that at some point as well.

**Comment by jimmyday12** [comment]
Sweet - I made some changes last night after a build failed so probably worth merging those changes into your branch before you do any more work

**Pull request merged**
