### PR TITLE
Add replace_venues function

### LINKED ISSUE #15: Add 'Replace Venues' function
Footywire venues are named differently to afltables. Write a function people can use to convert them

### PR DESCRIPTION
**Pull request by cfranklin11**
Resolves #15 

Different data sources use different naming conventions for
venues, which requires mapping to make them consistent for joins.
This change maps all known venue names to the corresponding
name in AFL Tables. We use AFL Tables, because it is the most
comprehensive data source and changes venue names less frequently
than others.

### CODE REVIEW

**Comment by jimmyday12** [comment]
Thanks @cfranklin11. I'm just in the middle of our first submission to CRAN (currently pending review) so I'll just hold off merging until that process finishes. Then I'll bump to a development version and merge this in.

**Comment by jimmyday12** [comment]
@cfranklin11 OK - all good to get this merged in. Just noticed some conflicts that might need fixing. Make sure you also add a new bullet point in NEWS.md under 0.2.0.9000

**Comment by jimmyday12** [comment]
@cfranklin11 See my other comment - good to get this merged in but some conflicts exist now. If you can fix them up I'll get it merged in :) Don't forget the bulletpoint in news.md

**Comment by cfranklin11** [comment]
There seems to be an issue with caching `apt` packages in Travis CI that causes errors when installing dependencies. The last commit seems to fix it, but let me know if you find a better alternative.

**Comment by cfranklin11** [comment]
@jimmyday12 I updated `replace_venues` to cover a recent name change on Footywire (I guess GWS changed the name of their stadium?). Due to the Travis CI fix in the last commit, I think it makes sense to merge this, then I can resolve any conflicts on #92, or I can make the Travis CI fix its own PR if you prefer.

**Pull request merged**
