### PR TITLE
Added AFLW stats and test.

### PR DESCRIPTION
**Pull request by Fryzigg**

### CODE REVIEW

**Comment by jimmyday12** [comment]
Looks good to me - can you just add a bullet point to the `NEWS.md` file and I'll merge it in

**Comment by Fryzigg** [comment]
> Looks good to me - can you just add a bullet point to the `NEWS.md` file and I'll merge it in

Like that?

**Comment by Fryzigg** [comment]
Function isn't available within the development version of the package, believe because namespace hasn't been updated. Is there any extra step i need to take in the future to make functions callable.

**Comment by jimmyday12** [comment]
A good practice is to run `devtools::check(document = TRUE)` - this should run all checks but also update the namespace if needed. I can do that on Master now to update it

**Comment by Fryzigg** [comment]
Cool noted, thanks. Will do this in the future.

**Pull request merged**
