### PR TITLE
Fix round calculation

### LINKED ISSUE #93: Some round numbers are incorrect for footywire data sources
I came across a few issues with round numbers recently:

1. For `get_footywire_betting_data` the match on 2018-04-25 is in the wrong round due to the filter matching on date-time and betting data only having dates.

2. Requesting multiple seasons for `get_footywire_betting_data` results in incorrect round numbers if the request includes 2014, because it started on week 11, whereas the other valid seasons all started on week 12. This makes non-2014 seasons start on round 2 instead of 1.

3. A lot of round numbers are wrong in general largely due to all Sunday matches being off by one (e.g. Sunday matches in round 10 are actually labelled as being in round 11). Given that this worked before, I think it's due to `lubridate` changing how it calculates weekday numbers.

### PR DESCRIPTION
**Pull request by cfranklin11**
Resolves #93 

I came across a few issues with round numbers recently:

1. I must have missed this earlier, but the date filter for `"2018-04-25 15:20:00"` doesn't work for betting data, because it has dates only, no match start times. Normalising dates to remove times for the sake of matching fixes the problem.

2. Requesting multiple seasons for `get_footywire_betting_data` resulted in incorrect round numbers, if the request included 2014, because it started on week 11, whereas the other valid seasons all started on week 12. Grouping by season before calculating the minimum week number fixed this.

3. A lot of round numbers were wrong in general due to (I believe) a change in how `lubridate` calculates weeks & weekdays. I remember looking at the documentation, and it saying that Sunday is always 7 and Monday always 1, but now it's relative to when the week is set to start, with the default being Sunday. This means that by default, Sunday is 1 and Monday is 2. I left the default and changed the round week shift to start on Sunday instead of Monday now.

### CODE REVIEW

**Comment by cfranklin11** [comment]
I've noticed some `testthat::skip_on_cran()` in the test files, so let me know if I should add that to new tests. Also, I held off on updating `NEWS` with the bug fix since you're submitting the package to CRAN.

**Comment by jimmyday12** [comment]
> I've noticed some `testthat::skip_on_cran()` in the test files, so let me know if I should add that to new tests. Also, I held off on updating `NEWS` with the bug fix since you're submitting the package to CRAN.

Hi @cfranklin11 yeah sorry I missed this but CRAN forces you to have a test suite that run in <10s so given our tests usually involve API's/downloading data I've had to skip them all on CRAN. If you could include those it would be great :)

**Comment by cfranklin11** [comment]
@jimmyday12 I added the test skipping for CRAN and updated the docs/news, so this should be good to merge

**Comment by jimmyday12** [comment]
Looks great thanks @cfranklin11

**Pull request merged**
